# This rule is not used by the project configmap-sync-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to configsync.example.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: configmap-sync-operator
    app.kubernetes.io/managed-by: kustomize
  name: configmapsync-viewer-role
rules:
- apiGroups:
  - configsync.example.com
  resources:
  - configmapsyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configsync.example.com
  resources:
  - configmapsyncs/status
  verbs:
  - get
